# Generated by Django 4.1.7 on 2023-04-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('authors', models.CharField(blank=True, max_length=300, null=True)),
                ('isbn13', models.IntegerField(blank=True, null=True)),
                ('isbn10', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=150, null=True)),
                ('pubyear', models.IntegerField(blank=True, null=True)),
                ('subjects', models.CharField(blank=True, max_length=300, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
