# Generated by Django 4.1.7 on 2023-04-13 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_booksdetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksdetails',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.RegexValidator('[+-/%$]', inverse_match=True)]),
        ),
    ]
