# Generated by Django 4.1.7 on 2023-04-14 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_booksdetails_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksdetails',
            options={},
        ),
    ]
